version: "3"
services:
  nginx:
    container_name: DOCKED_nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/cert
      - ./conf:/conf
      - ./logs:/logs
      - ./code:/code
    networks:
      - DOCKED_network
networks:
  DOCKED_network:
    driver: bridge
